### ISSUE TITLE
[错误报告] 

### ISSUE THREAD

**Issue by TaylorEevee** [CaaMoe/MultiLogin#106]
### BUG描述

waterfall添加multilogin并开启皮肤修复后，皮肤站用户第一次进的子服皮肤是正常的，但是切换过服务器后皮肤丢失，即使切换回登录时的服务器皮肤任然丢失

### MultiLogin版本

0.6.5

### 系统架构

linux/amd64

### 服务器核心

purpur-1.20.1

### 配置文件

https://pastebin.com/H0eXbwuK

### 复现步骤

1.
2.
3.
...

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by Radiation-pi** [comment]
是这样的，看来也不只我一个遇到这个问题，话说Tay能看看我开的issue吗？是不是也有类似问题？

**Comment by TaylorEevee** [comment]
> 是这样的，看来也不只我一个遇到这个问题，话说Tay能看看我开的issue吗？是不是也有类似问题？

是的，一模一样，目前我是让用皮肤站登录原版的玩家装fabric用no chat reports mod暂时能进服，皮肤这个没啥办法

**Comment by CaaMoe** [comment]
使用0.6.6，再试一次吧
