### ISSUE TITLE
[错误报告]  0.6.6版本，外置登录报告无效的个人信息公钥签名

### ISSUE THREAD

**Issue by ShulkerSakura** [CaaMoe/MultiLogin#107]
### BUG描述

使用0.6.5就是一样的问题，昨天看到修复了非微软账号认证玩家登录服务器被踢出的问题，今天立刻更新了0.6.6，结果问题依旧
最开始考虑是启动器的问题，因为HMCL在Linux 上认证没有问题，在Windows 却会出现问题，去反馈后发现，User Type为Mojang时可以正常进入游戏，但是HMCL/PCL等启动器已经统一将外置认证更改为了“AuthInfo.USER_TYPE_MSA”是刻意为之，于是来给Multi Login 提issue

### MultiLogin版本

0.6.6

### 系统架构

Linux/amd64

### 服务器核心

purpur/spigot

### 配置文件

https://pastebin.mozilla.org/PFBMTB1G

### 日志

https://pastebin.mozilla.org/bcx5D8Zu

### 复现步骤

1.安装任意bukkit服务端
2.安装Multi Login 0.6.6
3.在Windows 上使用HMCL3.5.5（最新）或PCL2.6.3（最新）使用littleskin登录游戏
4.进入服务器后被踢出提示如标题

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by CaaMoe** [comment]
配置文件和日志链接过期了，请重新上传
