### ISSUE TITLE
[错误报告] Blessing Skin认证玩家的披风不显示，在Blessing Skin和官方 Yggdrasil同时开启skinRestorer时

### ISSUE THREAD

**Issue by XiaohCeale** [CaaMoe/MultiLogin#108]
### BUG描述

**问题**：将Blessing Skin验证的skinRestorer开启后，官方 Yggdrasil验证的玩家可以看见Blessing Skin验证玩家的皮肤，但不能看见披风，Blessing Skin验证玩家自身也是（即皮肤可以，披风不行）

**我做了**：将Blessing Skin验证的skinRestorer开启
&nbsp;&nbsp;&nbsp;&nbsp;**开启前**：官方 Yggdrasil验证的玩家无法看见Blessing Skin验证玩家的皮肤及披风（即为史蒂夫或艾利克斯）；但Blessing Skin验证的玩家可以看见官方 Yggdrasil验证玩家的皮肤以及披风
&nbsp;&nbsp;&nbsp;&nbsp;**开启后**：官方 Yggdrasil验证的玩家可以看见Blessing Skin验证玩家的皮肤，但不能看见披风；Blessing Skin验证的玩家仍然可以看见官方 Yggdrasil验证玩家的皮肤以及披风，但也看不见自己的披风

**期望**：Blessing Skin验证开启skinRestorer后，官方 Yggdrasil验证的玩家可以看见Blessing Skin验证玩家的披风，及皮肤

**实际**：Blessing Skin验证开启skinRestorer后，官方 Yggdrasil验证的玩家无法看见Blessing Skin验证玩家的披风，仅能看见皮肤

### MultiLogin版本

0.6.6

### 系统架构

linux/amd64

### 服务器核心

BungeeCord

### 配置文件

https://pastebin.mozilla.org/xKOFUgOW；https://pastebin.mozilla.org/ixTsbS8D；https://pastebin.mozilla.org/5zPDM1hF

### 日志

这个bug不产生错误日志，大概

### 复现步骤

1.  将Blessing Skin验证的skinRestorer开启
2.
3.
...

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by CaaMoe** [comment]
非常抱歉，根据原版mc的特性，我们做不到给原版端展示来自第三方的自定义披风。或许你能提供一些思路出来吗？

**Comment by HarukaB** [comment]
我觉得主要的问题应该是开启后外置登录的玩家也看不见自己的披风了，导致我只能一刀切，禁止正版登录了

**Comment by XiaohCeale** [comment]
> 我觉得主要的问题应该是开启后外置登录的玩家也看不见自己的披风了，导致我只能一刀切，禁止正版登录了

是的，后来我也发现不止正版不可见皮肤站披风，同皮肤站间披风也不可见。准备去再提一个issue

**Comment by XiaohCeale** [comment]
#138
