### ISSUE TITLE
外置登录被正版验证卡住[错误报告] 

### ISSUE THREAD

**Issue by YuSanr** [CaaMoe/MultiLogin#110]
### BUG描述

使用外置登录
进入之后是Minecraft 对 离线玩家进入正版服务器的提示
![image](https://github.com/CaaMoe/MultiLogin/assets/112278452/901d3dda-f835-4f8b-9f97-221734d52e02)
我的配置
![image](https://github.com/CaaMoe/MultiLogin/assets/112278452/6da5f387-19d3-4041-82c3-c58e1086d7c5)
![image](https://github.com/CaaMoe/MultiLogin/assets/112278452/7fd7c215-6a35-40a7-8a04-64234f9201ed)
正版照常进入
![image](https://github.com/CaaMoe/MultiLogin/assets/112278452/86f6becf-813e-4db3-b167-7cd41fa3fa99)

### MultiLogin版本

0.6.6-0.6.5

### 系统架构

linux

### 服务器核心

WaterFall 1.20-536

### 配置文件

如上图

### 日志

无报错

### 复现步骤

1. 开启正版验证
2. 添加皮肤站
3. 使用皮肤站登录
4. 进入服务器
...

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by Becods** [comment]
![image](https://github.com/CaaMoe/MultiLogin/assets/35525491/9ad57e44-687b-4825-8aad-db2fc786bf3d)
无法复现

**Comment by LIPiston** [comment]
检查一下这个皮肤站是不是卡顿还是怎么了
问题不在插件，是客户端无法和皮肤站沟通
