### ISSUE TITLE
添加完第三方皮肤站登录配置后一直登录不进去[错误报告] 

### ISSUE THREAD

**Issue by happytbs** [CaaMoe/MultiLogin#111]
### BUG描述

我在services文件夹里按照示例写了一个正确的配置，但是重启服务器后一直跟我说没有添加正确的目录树
![image](https://github.com/CaaMoe/MultiLogin/assets/74001578/2b26b5f5-9247-4d34-ac82-013466481193)

### MultiLogin版本

0.6.6

### 系统架构

windows/amd64

### 服务器核心

purper

### 配置文件

https://pastebin.com/5BmpaRqk

### 日志

https://pastebin.com/yNHjeTPU

### 复现步骤

1.把配置扔进services文件夹里
2.启动服务器
3.报错，进不去

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by happytbs** [comment]
服务端版本 purpur-1.20.1-2023

**Comment by Becods** [comment]
```
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 46, column 3:
      trackIp: false
      ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 95, column 5:
        url: 'https://example.com/sessio ... 
        ^
```
配置文件格式有误，请严格按照格式填写

**Comment by happytbs** [comment]
> ```
> Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
>  in 'reader', line 46, column 3:
>       trackIp: false
>       ^
> expected <block end>, but found '<block mapping start>'
>  in 'reader', line 95, column 5:
>         url: 'https://example.com/sessio ... 
>         ^
> ```
> 
> 配置文件格式有误，请严格按照格式填写

请问是哪里的配置，我没有在.env里找到这些代码
