### ISSUE TITLE
[错误报告] JE 无法正确显示 BE 玩家皮肤（FloodGate）

### ISSUE THREAD

**Issue by Pigeon0v0** [CaaMoe/MultiLogin#113]
### BUG描述

服务端安装了 Geyser+FloodGate+MultiLogin，但是皮肤仅单向可见（JE 仅可见 JE 皮肤，BE 可见 BE 和 JE 皮肤）

### MultiLogin版本

0.6.6

### 系统架构

Linux/amd64

### 服务器核心

Paper

### 配置文件

https://pastebin.com/uSCWGe8k

### 日志

https://pastebin.com/6nb1vUbL

### 复现步骤

应当无关

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by bwtx2023** [comment]
附注：日志中的 IP 和玩家聊天 / 指令信息已删去

目前正在尝试使用 SkinRestorer 插件临时解决皮肤问题

**Comment by CaaMoe** [comment]
目前对floodgate的支持仍在测试，floodgate没有一个好的api来处理这方面的需求，唯一能用的api已被弃用，请等待floodgate版本更新。

**Comment by CaaMoe** [comment]
基岩皮肤的支持好了，在floodgate他们修复event的问题之前，西药使用这个版本的floodgate才能正常显示be皮肤 https://github.com/CaaMoe/Floodgate
