### ISSUE TITLE
[错误报告] wiki 中的档案相关命令参数有误

### ISSUE THREAD

**Issue by nkxingxh** [CaaMoe/MultiLogin#114]
### BUG描述

wiki 中的档案相关命令有参数缺漏。

比如：
```
/multilogin profile set <档案信息> <在线信息>

权限: command.multilogin.profile.set.other
描述: 设置指定目标登录的游戏档案。
参数
<档案信息> 指定登录的档案
<在线信息> 指定目标
```

实际上应该是 `/multilogin profile set <档案信息> <服务ID> <在线信息>`

### MultiLogin版本

--

### 系统架构

--

### 服务器核心

--

### 配置文件

--

### 复现步骤

1.
2.
3.
...

### 确认一遍

- [ ] 我已完成且认真地填写完了报告所需要的信息
- [x] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by CaaMoe** [comment]
在这 https://github.com/CaaMoe/MultiLogin/wiki#%E6%8C%87%E4%BB%A4%E8%AF%B4%E6%98%8E

**Comment by Becods** [comment]
请认真阅读wiki
不过wiki编写得确实会导致理解上的问题

> ## 指令和配置
> 
> ### 指令说明
> 
> * `<参数>` 为必填指令
> * `[参数]` 为可选指令
> * 参数 `<在线信息>` 表示 `<ServiceId> <在线UUID|在线名字>` 的简写，表示一个在线身份信息。
> * 参数 `<档案信息>` 表示 `<档案名字|档案UUID>` 的简写，表示一个游戏内的档案信息。
