### ISSUE TITLE
[错误报告] 1.20.2更新后出现无法登录问题

### ISSUE THREAD

**Issue by Entity616** [CaaMoe/MultiLogin#116]
### BUG描述

更新1.20.2后出现无法登录问题
包括正版登录和外置登录
启动时无报错
玩家无法进入，客户端提示“Failed to verify username!”
更新前一切正常

### MultiLogin版本

v0.6.6

### 系统架构

windows/amd64

### 服务器核心

paper

### 配置文件

https://pastebin.com/KVpEEEX0

### 日志

https://pastebin.com/U9Pd6Zt8

### 复现步骤

1.关闭运行正常的1.20.1服务器
2.更新paper1.20.2
3.更新ProtocolLib
4.开启服务器
5.玩家无法进入游戏，服务器后台出现报错

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by CaaMoe** [comment]
#115 请在Github ci中获得最新版本的下载
