### ISSUE TITLE
[建议] 希望MultiLogin能预留一个与客户端的数据传输通道(例如CustomSkinLoader)

### ISSUE THREAD

**Issue by 8MiYile** [CaaMoe/MultiLogin#118]
### 描述功能请求

比如说CustomSkinLoader客户端插件（以下简称CSL插件） 因为服务器使用了MultiLogin但是CSL插件却不能正确的分配用户的皮肤，因为无法获取到用户的登录类型，想知道说会不会为此模组增加一个信道，带ModName+Token的验证方式方便CSL插件与MultiLogin插件的交互

### 请确认此建议所影响的内容

- [ ] 文档
- [ ] 安装
- [ ] 可扩展性
- [ ] 安全
- [X] 用户体验
- [ ] 测试和发布
- [ ] 开发架构
- [X] 新的扩展
- [ ] 其他

**Comment by 8MiYile** [comment]
请求类型就是 ModID+ModToken+要查询的用户名 返回的可以是type=name,string=microsoft或者是type=name,string=littleskin 再或者就是 type=url,string=https://xxxx

**Comment by Becods** [comment]
这是csl的问题
安装了ml的服务器，不需要csl来获取皮肤

所以你为何不直接调整优先级
亦或者让用户删除csl
```
  "loadlist": [
    {
      "name": "Your Skin",
      "type": "CustomSkinAPI",
      "root": "https://yourskin.here"
    },
    {
      "name": "Mojang",
      "type": "MojangAPI",
      "apiRoot": "https://api.mojang.com/",
      "sessionRoot": "https://sessionserver.mojang.com/"
    }
  ]
  ```

**Comment by 8MiYile** [comment]
若已在服务器修复了 那能否留一个MultiLoginIsLoaded的接口 直接返回true的

**Comment by CaaMoe** [comment]
你或许可以关闭 MultiLogin 的皮肤修复功能来让 CustomSkinLoader 生效
________________________________
发件人: 8Mi_Yile ***@***.***>
发送时间: 2023年10月16日 11:11
收件人: CaaMoe/MultiLogin ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [CaaMoe/MultiLogin] [建议] 希望MultiLogin能预留一个与客户端的数据传输通道(例如CustomSkinLoader) (Issue #118)


若已在服务器修复了 那能否留一个MultiLoginIsLoaded的接口 直接返回true的

―

**Comment by Silverteal** [comment]
使用MultiLogin并在服务器**启用在线模式**后，它会直接向服务器内玩家发送玩家用于登录的皮肤，所以不需要使用CSL。CSL会替换客户端的皮肤获取逻辑，反而有可能破坏MultiLogin的工作方式。

**Comment by 8MiYile** [comment]
原来Vanilla支持这个特性了啊，那我关闭了
