### ISSUE TITLE
[错误报告] Geyser(Floodgate)无法运行/进入服务器

### ISSUE THREAD

**Issue by HansOffice** [CaaMoe/MultiLogin#120]
### BUG描述

安装插件设置完成后基岩版玩家无法进入服务器
错误信息为：（xxx因为尝试以Java版玩家身份登录！Floodgate设置正确吗？与Java服务器断开了连接）
已尝试的手段为：config内floodgateSupport: 选项设置为false(该bug依旧存在)
floodgateSupport: 选项设置为true(bug依旧存在)
services文件夹内存在floodgate文件(bug依旧存在)
services文件夹内不存在floodgate文件（bug依旧存在）

### MultiLogin版本

v0.6.6

### 系统架构

windows

### 服务器核心

waterfall1.20.1

### 配置文件

config的配置文件https://pastebin.com/06micfjQ
floodgate的配置文件https://pastebin.com/ss31FBTY

### 日志

waterfall日志https://pastebin.com/xLACQS9b
独立版geyser日志https://pastebin.com/6EFPbZv7

_No response_

### 复现步骤

1.将floodgateSupport改为false（或改成true并启用services文件夹内的floodgate文件）
2.使用基岩版进入服务器
3.出现（xxx因为尝试以Java版玩家身份登录！Floodgate设置正确吗？与Java服务器断开了连接）问题无法进入服务器
4.关闭此插件基岩版玩家可以重新进入服务器，并且Floodgate有在正常运行
...

### 确认一遍

- [ √] 我已完成且认真地填写完了报告所需要的信息
- [ √] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by CaaMoe** [comment]
```
# floodgate 支持
# 启用此闸门支持将会代理 floodgate 入口以让猫踢螺钉控制 floodgate 入口的玩家档案
#
# 警告：此功能将会使 floodgate 的账户连接功能失效，包括全球连接！
# 默认组 false
floodgateSupport: true
```
还差一步，在MultiLogin的配置文件中将 floodgateSupport 改为 true

**Comment by HansOffice** [comment]
> ```
> # floodgate 支持
> # 启用此闸门支持将会代理 floodgate 入口以让猫踢螺钉控制 floodgate 入口的玩家档案
> #
> # 警告：此功能将会使 floodgate 的账户连接功能失效，包括全球连接！
> # 默认组 false
> floodgateSupport: true
> ```
> 
> 还差一步，在MultiLogin的配置文件中将floodgateSupport改为true

我上面说了，这个就算是设置成true依旧会出现（因为xxx尝试以Java版玩家身份登录！Floodgate设置正确吗？与Java服务器断开了连接）这样的问题，依旧是无法进入服务器

**Comment by HansOffice** [comment]
> ```
> # floodgate 支持
> # 启用此闸门支持将会代理 floodgate 入口以让猫踢螺钉控制 floodgate 入口的玩家档案
> #
> # 警告：此功能将会使 floodgate 的账户连接功能失效，包括全球连接！
> # 默认组 false
> floodgateSupport: true
> ```
> 
> 还差一步，在MultiLogin的配置文件中将floodgateSupport改为true

如果可以，我想获得可以正常进入的交流群聊，这样反馈交流问题或许会更有效率

**Comment by CaaMoe** [comment]
目前只在 Bungee 版本上出现这个问题，Velcoity 没有复现，而处理闸门登录的部分代码是完全相同的，近期可能不会获得比较好的解决方案

**Comment by HansOffice** [comment]
> 目前只在 Bungee 版本上出现这个问题，Velcoity 没有复现，而处理闸门登录的部分代码是完全相同的

有什么解决方式吗？bungee与waterfall目前都是这么个情况，无论开启或是关闭基岩版玩家都被拦截在外

**Comment by CaaMoe** [comment]
暂时没有什么好的解决方案，你可以尝试更换velocity来使用

**Comment by HansOffice** [comment]
> 暂时没有什么好的解决方案，你可以尝试更换velocity来使用

啊这，velocity的插件支持和bungee的插件支持似乎是完全不一样的吧，更换一次服务端核心需要更换并且重新配置的东西似乎挺多的

**Comment by CaaMoe** [comment]
> > ```
> > # floodgate 支持
> > # 启用此闸门支持将会代理 floodgate 入口以让猫踢螺钉控制 floodgate 入口的玩家档案
> > #
> > # 警告：此功能将会使 floodgate 的账户连接功能失效，包括全球连接！
> > # 默认组 false
> > floodgateSupport: true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 还差一步，在MultiLogin的配置文件中将floodgateSupport改为true
> 
> 如果可以，我想获得可以正常进入的交流群聊，这样反馈交流问题或许会更有效率

为什么进不去呢

**Comment by HansOffice** [comment]
> > > ```
> > > # floodgate 支持
> > > # 启用此闸门支持将会代理 floodgate 入口以让猫踢螺钉控制 floodgate 入口的玩家档案
> > > #
> > > # 警告：此功能将会使 floodgate 的账户连接功能失效，包括全球连接！
> > > # 默认组 false
> > > floodgateSupport: true
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 还差一步，在MultiLogin的配置文件中将floodgateSupport改为true
> > 
> > 
> > 如果可以，我想获得可以正常进入的交流群聊，这样反馈交流问题或许会更高效率
> 
> 为什么进不去呢

入群问题始终回答错误，我并不知道正确的入群问题答案，将入群问题写的Yg_d_as_l给写上去也是错误的

**Comment by CaaMoe** [comment]
尝试修复了一下，你可以到github ci中获得最新版本的下载

**Comment by HansOffice** [comment]
> 尝试修复因果，你可以到github ci中获得最新版本的下载

可以发布到Releases吗？我并不知道如何将代码构建成jar文件

**Comment by CaaMoe** [comment]
https://github.com/CaaMoe/MultiLogin/actions/runs/6634631436

**Comment by HansOffice** [comment]
> https://github.com/CaaMoe/MultiLogin/actions/runs/6634631436



> https://github.com/CaaMoe/MultiLogin/actions/runs/6634631436

好的，已确定新版本已修复了，我已经测试了
