### ISSUE TITLE
在更新到0.6.7之后就开始报错[错误报告] 

### ISSUE THREAD

**Issue by znc15** [CaaMoe/MultiLogin#125]
### BUG描述

从0.6.6更新到0.6.7之后的提示这个,用0.6.6正常进入

### MultiLogin版本

0.6.7

### 系统架构

linux/amd64

### 服务器核心

purpur-1.20.1

### 配置文件

https://pastebin.com/LxWu63aJ

### 日志

https://pastebin.com/c0MPyEDb

### 复现步骤

1.
2.
3.
...

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by CaaMoe** [comment]
已在[这次提交](https://github.com/CaaMoe/MultiLogin/commit/cbc7f48ec3273148e0ef8b8bac2d054f2d50cc04)中修复，感谢反馈
