### ISSUE TITLE
[错误报告] 0.6.7在paper服务端上阻止玩家连接服务器

### ISSUE THREAD

**Issue by LrbsX** [CaaMoe/MultiLogin#127]
### BUG描述

1.下载multilogin 0.6.7 bukkit
2.安装到paper服务端
3.设置正版和Littleskin连接
4.打开服务端
5.正版/皮肤站玩家连接
6.失败
7.退回到0.6.5，成功
希望修复0.6.7的问题。

log如下
[latest.log](https://github.com/CaaMoe/MultiLogin/files/13546049/latest.log)

配置文件
MultiLogin配置文件无改动
[server.properties.txt](https://github.com/CaaMoe/MultiLogin/files/13546099/server.properties.txt)
[paper-global.yml.txt](https://github.com/CaaMoe/MultiLogin/files/13546103/paper-global.yml.txt)
[littleskin.yml.txt](https://github.com/CaaMoe/MultiLogin/files/13546127/littleskin.yml.txt)
[offical.txt](https://github.com/CaaMoe/MultiLogin/files/13546128/offical.txt)
![image](https://github.com/CaaMoe/MultiLogin/assets/95033532/ad89d39e-5a44-4ded-9018-12652cc743c5)

### MultiLogin版本

multilogin-0.6.7-bukkit

### 系统架构

windows/amd64

### 服务器核心

paper-1.20.1-build196

### 配置文件

如主描述

### 日志

如主描述

### 复现步骤

如主描述

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by CaaMoe** [comment]
重复的 https://github.com/CaaMoe/MultiLogin/issues/125
