### ISSUE TITLE
[错误报告] 使用部分指令时出现提示：无法解析指令 Cannot read the array length because "bytes" is null。

### ISSUE THREAD

**Issue by Glucy-2** [CaaMoe/MultiLogin#128]
### BUG描述

要给LittleSkin登录的玩家添加一个正版登录方式
<img width="640" alt="image" src="https://github.com/CaaMoe/MultiLogin/assets/53287753/21f07152-9981-4f8a-8859-c9df610fc382">
尝试使用指令`/multilogin profile set 1d5d9d29-27b7-3fc1-8963-9e02e0e37122 0 57ea57a9-e31c-40aa-8f39-28ca02554a19`，`/multilogin profile set sain 0 57ea57a9-e31c-40aa-8f39-28ca02554a19`和`/multilogin whitelist specific add 0 57ea57a9-e31c-40aa-8f39-28ca02554a19`都是如标题所述的提示

### MultiLogin版本

0.6.7

### 系统架构

linux/amd64

### 服务器核心

velocity-3.2.0-SNAPSHOT-296 / velocity-3.3.0-SNAPSHOT-306

### 配置文件

https://pastebin.com/bgcZQQnT

### 日志

https://pastebin.com/kVQFVPZC

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by KiWinger** [comment]
是的只有v端装该插件时，子服无法使用v端的插件指令

**Comment by Glucy-2** [comment]
> 只有v端装该插件时

我在游戏内和V端控制台都报错，另外这个插件是只装在最外层用的，子服不需要装，我fabric也没法装

>  你可以试试是不是所有指令都无法使用？

查询类的指令是可以用的，具体我没全试

**Comment by Glucy-2** [comment]
使用`/multilogin whitelist add <用户名|UUID>`添加缓冲白名单，插件显示成功，但是玩家进不去，数据库里面`multilogin_cache_whitelist`也没有添加的的用户名或UUID
感觉是数据库的问题，是因为不兼容MariaDB（`10.11.4-MariaDB-1~deb12u1`）吗？但是之前用的都没问题啊（？

**Comment by Glucy-2** [comment]
试了一下用H2数据库，还会有同样的问题
<img width="1099" alt="image" src="https://github.com/CaaMoe/MultiLogin/assets/53287753/ecf866c0-a02d-43da-9290-038da06c3304">

并且看数据库里面没有任何表（？
<img width="481" alt="image" src="https://github.com/CaaMoe/MultiLogin/assets/53287753/467029d1-0f2c-4ee4-89bc-f2571911f355">

**Comment by Glucy-2** [comment]
目前的临时解决方法是手动改数据库（
自己测了velocity版本`3.2.0-259`到`3.3.0-316`（multilogin版本`0.6.7`）都能复现该问题：
1. `multilogin profile create Glucy2 c4d02b32-7406-4fd8-b787-d558384f623c`
2. 尝试加入游戏（提示不在白名单）
3. `multilogin whitelist specific add 0 c4d02b32-7406-4fd8-b787-d558384f623c`
4. 出现问题
