### ISSUE TITLE
[错误报告] blessing skin皮肤修复失效

### ISSUE THREAD

**Issue by TaylorEevee** [CaaMoe/MultiLogin#129]
### BUG描述

启动后玩家加入，正版皮肤正常加载，但是使用blessing skin的玩家的皮肤无法加载，并且设置代理后查看代理日志发现没有流量经过

### MultiLogin版本

MultiLogin-Velocity-0.6.7

### 系统架构

linux/amd64，windows/amd64

### 服务器核心

velocity-3.3.0-SNAPSHOT-316

### 配置文件

https://pastebin.com/QFVsdLYE

### 日志

无

### 复现步骤

1.
2.
3.
...

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by CaaMoe** [comment]
日志提供一下下吧

**Comment by TaylorEevee** [comment]
> 日志提供一下下吧

https://pastebin.com/kH5TwzVw

**Comment by TaylorEevee** [comment]
发现问题了，我配置blssing skin的时候不小心把网站url给改了，我的问题
