### ISSUE TITLE
[错误报告] 处理登录请求时发生异常，请与服务器管理员取得联系。

### ISSUE THREAD

**Issue by Louyunz** [CaaMoe/MultiLogin#131]
### BUG描述

玩家无法加入服务器，后台提示处理登录请求时发生异常，请与服务器管理员取得联系。

### MultiLogin版本

v0.6.7

### 系统架构

windows/x64

### 服务器核心

Mohist - 1.18.2-136, Java(21.0.1) 65.0

### 配置文件

https://pastebin.com/MSeBSmiD

### 日志

https://pastebin.com/JDmqfFe1

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by Becods** [comment]
https://github.com/CaaMoe/MultiLogin/issues/74
