### ISSUE TITLE
[建议] 添加Placeholder 来确认玩家是否为正版玩家

### ISSUE THREAD

**Issue by 2188349576** [CaaMoe/MultiLogin#132]
### 描述功能请求

希望通过Placeholder的方法来添加一个变量
这样可在服务器内鼓励玩家使用正版Minecraft

### 请确认此建议所影响的内容

- [ ] 文档
- [ ] 安装
- [X] 可扩展性
- [ ] 安全
- [ ] 用户体验
- [ ] 测试和发布
- [ ] 开发架构
- [ ] 新的扩展
- [ ] 其他

**Comment by Becods** [comment]
必要性不是很高

Multilogin曾经做过PlaceholderAPI的支持，但是在前几个版本中被删除了

且Multilogin是偏代理端侧的插件，但代理端均无好用稳定的占位符
