### ISSUE TITLE
[错误报告] 皮肤站披风不可见

### ISSUE THREAD

**Issue by XiaohCeale** [CaaMoe/MultiLogin#138]
### BUG描述

使用皮肤站登录后，**玩家自身**及**同皮肤站**的其他玩家**互不可见**披风
![noml](https://github.com/CaaMoe/MultiLogin/assets/93030615/63ae28cd-fe11-4dc0-a3c7-0b5ebf2b4a24)
![ml-self](https://github.com/CaaMoe/MultiLogin/assets/93030615/f36b4199-c61c-4d52-873e-bb54a60a65ec)
![ml-other](https://github.com/CaaMoe/MultiLogin/assets/93030615/74d3b77f-91e5-4969-9778-a5b11ef649f4)

### MultiLogin版本

0.6.7

### 系统架构

windows/amd64

### 服务器核心

paper 1.20.4

### 配置文件

https://pastebin.mozilla.org/q2jUM413

### 确认一遍

- [ ] 我已完成且认真地填写完了报告所需要的信息
- [ ] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by CaaMoe** [comment]
Nothing to preview

**Comment by xiao-k233** [comment]
日志吧
