### ISSUE TITLE
[建议] 能否添加离线玩家也可登录？

### ISSUE THREAD

**Issue by Robert-200289** [CaaMoe/MultiLogin#144]
### 描述功能请求

能否添加离线玩家也可登录？我的服务器的玩家大多为离线，且因网络问题无法使用外置登录

### 描述你考虑过的备选方案

原本打算建议使用外置登录，可是因网络问题无法使用外置登录

### 请确认此建议所影响的内容

- [ ] 文档
- [ ] 安装
- [ ] 可扩展性
- [X] 安全
- [X] 用户体验
- [ ] 测试和发布
- [ ] 开发架构
- [X] 新的扩展
- [X] 其他

**Comment by Becods** [comment]
> 拒绝 安全性问题太大
不符合产品预期
