### ISSUE TITLE
[建议] 转载至minebbs

### ISSUE THREAD

**Issue by jdnjk** [CaaMoe/MultiLogin#145]
### 描述功能请求

rt

### 请确认此建议所影响的内容

- [ ] 文档
- [ ] 安装
- [ ] 可扩展性
- [ ] 安全
- [ ] 用户体验
- [ ] 测试和发布
- [ ] 开发架构
- [ ] 新的扩展
- [X] 其他

**Comment by jdnjk** [comment]
https://mcbbs.run/t/topic/307一处未知转载情况

**Comment by CaaMoe** [comment]
已转载
https://www.minebbs.com/resources/multilogin.7521/
https://mcbbs.run/t/topic/307
https://klpbbs.com/thread-130564-1-1.html

**Comment by SuperYYT** [comment]
> 已转载 https://www.minebbs.com/resources/multilogin.7505/ https://mcbbs.run/t/topic/307 https://klpbbs.com/thread-130564-1-1.html

原则上我们会更支持原创作者发布，如果有需要，我们可以清理转载资源
