### ISSUE TITLE
[错误报告] 所有指令都提示 “指令参数不正确”

### ISSUE THREAD

**Issue by KiWinger** [CaaMoe/MultiLogin#146]
### BUG描述

登录操作一切正常，设置中“welcomeMsg: true”也会正常执行，仅所有指令无效。
键入时无 Tab 提示，键入任何指令均返回 “指令参数不正确”，仅键入 /multilogin 时返回 “未知的指令”。
控制台无任何反应，下面填的两个版本均如此。

### MultiLogin版本

0.6.7 / Build_188f2de

### 系统架构

Windows 10 pro / X64

### 服务器核心

velocity-3.2.0-SNAPSHOT-296 / velocity-3.3.0-SNAPSHOT-367

### 配置文件

https://pastebin.com/3aw2VNGP

### 复现步骤

1.
2.
3.
...

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by CaaMoe** [comment]
因为使用的是brigadier，在没有权限时会提示命令参数不正确且不能补全指令，请检查权限

**Comment by KiWinger** [comment]
1.自始至终玩家都处于OP状态下
2.于子服使用 LP 给予 user 权限 command.multilogin.list
3.于子服内使用指令 /multilogin list 或使用 /multilogin
4.返回与之前一样的结果

**Comment by KiWinger** [comment]
> 因为使用的是brigadier，在没有权限时会提示命令参数不正确且不能补全指令，请检查权限

1.自始至终玩家都处于OP状态下
2.于子服使用 LP 给予 user 权限 command.multilogin.list
3.于子服内使用指令 /multilogin list 或使用 /multilogin
4.返回与之前一样的结果

**Comment by CaaMoe** [comment]
你需要在velocity端上给予使用权限而不是后端

**Comment by KiWinger** [comment]
> 你需要在velocity端上给予使用权限而不是后端

蛤？awa? 中转端权限？
这该如何给到？登陆默认就是进入子服……
我的前端是有安装LP的，但是貌似操作不到那边吧……

**Comment by CaaMoe** [comment]
luckperms有velocity版本，用lpv
