### ISSUE TITLE
paper无法使用其登录

### ISSUE THREAD

**Issue by 090424xsp** [CaaMoe/MultiLogin#148]
### BUG描述

使用MultiLogin登录服务器时提示"处理登录请求时发生异常，请与服务器管理员取得联系。"(日志最下方)

### MultiLogin版本

v0.6.7

### 系统架构

Windows 10 10.0 (amd64)

### 服务器核心

paper-1.20.1

### 配置文件

https://pastebin.mozilla.org/gtNVana5

### 日志

https://pastebin.mozilla.org/wSgK8p3x

### 复现步骤

1.放入插件
2.开启服务器
3.使用皮肤站登录
4.报错并拒绝登录

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by CaaMoe** [comment]
重复的 #125
