### ISSUE TITLE
[Bug Report] 多次登录均显示：由于服务器网辂问题，或是账户验证服务器返回了个意料之外的结果，导 致暂时不能验证您的会话信息，请重试。

### ISSUE THREAD

**Issue by happytbs** [CaaMoe/MultiLogin#150]
### Bug Description

多次登录均显示：由于服务器网辂问题，或是账户验证服务器返回了个意料之外的结果，导 致暂时不能验证您的会话信息，请重试。
更换网络无法解决

### MultiLogin Version

0.6.7

### System Architecture

windows/amd64

### Server Core

mohist1.18.2

### Configuration file

https://pastebin.com/N1P9WB79

### Logs

https://mclo.gs/aLjiKwa

### Steps to reproduce

1.编写配置文件
2.重启服务器
3.进入服务器
4.报错

### Affected area

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by ShawnMerryCode** [comment]
This issue is a bug,but we can't fix it.

**Comment by CaaMoe** [comment]
如果不是特别必要，不要使用 CUSTOM_YGGDRASIL。StarfishSkin请使用BLESSING_SKIN，否则请完善验证URL为 'https://skin.tbstmc.xyz/api/yggdrasil/sessionserver/session/minecraft/hasJoined?username={username}&serverId={serverId}{ip}'

**Comment by happytbs** [comment]
> 如果不是特别必要，不要使用 CUSTOM_YGGDRASIL。StarfishSkin请使用BLESSING_SKIN，否则请完善验证URL为 '[https://skin.tbstmc.xyz/api/yggdrasil/sessionserver/session/minecraft/hasJoined?username={username}&serverId={serverId}{ip}](https://skin.tbstmc.xyz/api/yggdrasil/sessionserver/session/minecraft/hasJoined?username=%7Busername%7D&serverId=%7BserverId%7D%7Bip%7D)'

我们尝试过了使用BLESSING_SKIN，但是错误仍然出现

**Comment by CaaMoe** [comment]
开启插件debug，再试一下然后把日志发出来

**Comment by happytbs** [comment]
> 开启插件debug，再试一下然后把日志发出来

https://mclo.gs/u8v0GXI

**Comment by happytbs** [comment]
> > 开启插件debug，再试一下然后把日志发出来
> 
> https://mclo.gs/u8v0GXI

这个是CUSTOM_YGGDRASIL，并且链接是按照你给的配置改了的

**Comment by CaaMoe** [comment]
请使用最新的周版，不要使用0.6.7

**Comment by happytbs** [comment]
> 请使用最新的周版，不要使用0.6.7

感谢，目前已经恢复正常
