### ISSUE TITLE
[错误报告] 无法加载插件

### ISSUE THREAD

**Issue by IlyaYezerovsky** [CaaMoe/MultiLogin#154]
### BUG描述

在1.12.2 CatServer上尝试使用Multilogin Bukkit 0.6.7，启动时显示无法加载插件（`Could not load 'plugins\MultiLogin-Bukkit-0.6.7.jar' in folder 'plugins'`）．之后服务器在不加载该插件的情况下正常启动．

### MultiLogin版本

Bukkit 0.6.7

### 系统架构

windows/x64

### 服务器核心

catserver

### 配置文件

无法加载插件，更无法生成配置文件！

### 日志

https://mclo.gs/VcYEGLi （line 1355）

### 复现步骤

1.用CatServer服务端，将此插件丢件plugins文件夹
2.启动服务器
3.出现问题

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by CaaMoe** [comment]
不支持混合端，一定要使用的话请用 velocity 版
