### ISSUE TITLE
[错误报告] 正则似乎判断有时失误

### ISSUE THREAD

**Issue by gyc123456-1** [CaaMoe/MultiLogin#164]
### BUG描述

符合正则表达式的玩家可能无法进入服务器

### MultiLogin版本

0.6.8

### 系统架构

windows/amd64

### 服务器核心

Velocity

### 配置文件

https://mclo.gs/ejSgEXO

### 日志

https://mclo.gs/6Pgk6Fy

### 复现步骤

更改后重启，等玩家进入即可

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by CaaMoe** [comment]
`Meatcry_.` 可能包含小数点导致正则无法通过验证
