### ISSUE TITLE
[Bug Report] MultiLogin v0.6.8该版本自动删除服务yml配置

### ISSUE THREAD

**Issue by passworked** [CaaMoe/MultiLogin#165]
### Bug Description

传了两个验证，一个正版，一个第三方，第三方配置文件在每次启动都会被清除

### MultiLogin Version

v0.6.8

### System Architecture

linux/amd64

### Server Core

velocity&fabric

### Configuration file

https://pastebin.com/X3ngvE7T

### Steps to reproduce

1.
2.
3.
...

### Affected area

- [ ] I included all information required in the sections above
- [ ] I made sure there are no duplicates of this report [(Use Search)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by CaaMoe** [comment]
请确保配置目录是在`services`下而不是在`example`下
