### ISSUE TITLE
[错误报告] 插件在Velocity加载失败

### ISSUE THREAD

**Issue by liangcha385** [CaaMoe/MultiLogin#168]
### BUG描述

我尝试在Velocity上加载此插件，但是它在没有加装其他插件的情况下依旧不起作用

### MultiLogin版本

MultiLogin v0.6.8

### 系统架构

windows/amd64

### 服务器核心

Velocity - 3.3.0-SNAPSHOT (git-2d015cdf-b397)

### 配置文件

https://pastebin.mozilla.org/qLiw4QvY

### 日志

https://pastebin.mozilla.org/7VsDBWX8

### 复现步骤

1.将插件装载到 Velocity 上
2.首次启动后停止 Velocity 并启用 littleskin 和 official 登录方式
3.启用 modern 转发
4.再次启动，复现错误

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by Becods** [comment]
[Weekly Ver](https://github.com/CaaMoe/MultiLogin/releases/tag/weekly) 已修复
