### ISSUE TITLE
[建议] 是否有计划支持authme等离线验证插件

### ISSUE THREAD

**Issue by Ceale** [CaaMoe/MultiLogin#169]
### 描述功能请求

使得离线登录的玩家也可以进入服务器

### 请确认此建议所影响的内容

- [X] 文档
- [X] 安装
- [ ] 可扩展性
- [ ] 安全
- [X] 用户体验
- [ ] 测试和发布
- [ ] 开发架构
- [ ] 新的扩展
- [ ] 其他

**Comment by PonderFox0643** [comment]
据 猫踢群（MultiLogin综合交流群）公告 片段


>以下违者一律禁言一天起
>
> ........
>
>**讨论离线+正版**
>........

群里不允许讨论有关离线版和正版混用这个事情的
估计也不太可能支持离线版
**当然，我不属于开发成员，仅仅只是猫踢的用户，具体还是看看开发成员怎么说**

**Comment by Ceale** [comment]
好的，明白了，感谢回复
