### ISSUE TITLE
盗版（无登录服务器）支持

### ISSUE THREAD

**Issue by MAX-XiaoKui** [CaaMoe/MultiLogin#17]
服务器有盗版玩家，无登录服务器，还有[PojavLauncher](https://github.com/PojavLauncherTeam/PojavLauncher)（手机上的Java版启动器，不支持外置登录）和基岩版（用[Geyser](https://github.com/GeyserMC/Geyser)连接至服务器）用户，所以盗版用户比较多
（保守估计不能/不会用正版/外置登录的玩家超过20%）
所以建议在所有服务器都验证失败后使用盗版登录（并且支持Velocity）
（如果可以的话）提供一个简单的登录系统防止他人使用账号

**Comment by ksqeib445** [comment]
拒绝 安全性问题太大

**Comment by KaltsitMoe** [comment]
你用外置登录就是为了安全性，你还要求盗版登录？
再说了，Geyser是可以外置登录的，没试就来说？
可笑

**Comment by CaaMoe** [comment]
基于分析 yggdrasil 机制，服务器验证失败的前提是客户端验证成功。这不是我们能控制得了的。有关于混合验证登入插入离线登入，这样做风险太大。

你仍然可配合FastLogin和Authlib-injector做到类似的效果（不推荐），MultiLogin不提供相关功能支持。

**Comment by BecodReyes** [comment]
首先，爱用用不用滚，就是这么个道理
> 我说话不好听，但是我觉得话糙理不糙，有的时候语气什么的太软了反而容易被用户当软柿子捏


问你外置登录是为了便捷还是安全？
都不是？
是因为要`支持Velocity`的登录插件吧
既然你用上了snap那不如直接上蹦极的插件不可？也不可能全部都不支持吧

**捐赠了么？**
开发者也是人，开发要吃喝，吃喝都要钱，不如这笔你来付？
那还不如找定制插件，那还便宜一点

开发者不是免费劳工，没有义务为你操办好所有
设身处地想一想这是不是一个可以完成的任务，完成之后会给主线功能造成多大影响，提issue语气态度诚恳一些，可以？

**Comment by MAX-XiaoKui** [comment]
谢谢回复，认识到错误了

**Comment by BecodReyes** [comment]
[XXMA16/BlitzLogi](https://github.com/XXMA16/BlitzLogin)
基本符合你想要的东西
与MultiLogin的兼容性暂未测试
如果issue开了记得关一下

**Comment by MAX-XiaoKui** [comment]
Thanks.
