### ISSUE TITLE
sql连接不支持sha265及缓存sha2认证插件

### ISSUE THREAD

**Issue by ZSXB2468** [CaaMoe/MultiLogin#172]
### BUG描述

在我尝试使用数据库连接时，假如账户验证方式设置为sha2则无法连接成功

### MultiLogin版本

MultiLogin v0.6.10 on Velocity - 3.3.0-SNAPSHOT (git-4eae510f-b402)

### 系统架构

linux/amd64

### 服务器核心

velocity

### 配置文件

https://pastebin.com/ZBgSqdn7         password：HLtSaH7rpm

### 日志

见复现步骤

### 复现步骤

![Clip_20240715_184840](https://github.com/user-attachments/assets/2d1e0404-67ae-4e9f-8515-dcbac20b5eb5)

启动即报错

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by Becods** [comment]
启用allowPublicKeyRetrieval
```
  # 高级设定，指定连接 URL
  #
  # 默认值 ’‘
  connectUrl: 'jdbc:mysql://127.0.0.1:3306/minecraft_multilogin?allowPublicKeyRetrieval=true'
  ```
