### ISSUE TITLE
[错误报告] 1.19+使用littleskin验证时出现Failed to verify Services signature

### ISSUE THREAD

**Issue by Entity616** [CaaMoe/MultiLogin#174]
### BUG描述

1.19+使用外置登录时出现Failed to verify Services signature，无法进入游戏
enforce-secure-profile=false

### MultiLogin版本

v0.6.11

### 系统架构

windows/amd64

### 服务器核心

paper-1.20.6-148

### 配置文件

https://pastebin.mozilla.org/wtGHUFts

### 日志

https://pastebin.mozilla.org/YYXaJvXs

### 复现步骤

1.paper-1.20.6-148
2.配置littleskin验证
3.出现错误，无法进入游戏
...

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by Becods** [comment]
重复 https://github.com/CaaMoe/MultiLogin/issues/163
