### ISSUE TITLE
[错误报告] 在 arclight 1.21-SNAPSHOT 核心使用时连接显示“验证用户名失败”

### ISSUE THREAD

**Issue by xk2013** [CaaMoe/MultiLogin#178]
### BUG描述

我启用了正版 和 littleskin 皮肤站的验证，但是当我使用 littleskin 账号登录时，显示用户名验证失败，使用 authlib-injector 都是正常的，所以肯定不是我账号的问题。

### MultiLogin版本

v0.6.11

### 系统架构

linux/amd64

### 服务器核心

arclight

### 配置文件

https://note.ms/orsx

### 日志

https://note.ms/fcnv

### 复现步骤

1. 下载 arclight-1.21-SNAPSHOT 服务端并安装 MultiLogin 插件启动。
2. 启用 offical 和 littleskin 配置文件。
3. 用 littleskin 登录的客户端连接服务器。

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by Becods** [comment]
缺少必要日志，默认视为 https://github.com/CaaMoe/MultiLogin/issues/153
