### ISSUE TITLE
[错误报告] MuiltLogin在Velocity 3.4.0-SNAPSHOT-#444中不可用

### ISSUE THREAD

**Issue by yeying-xingchen** [CaaMoe/MultiLogin#182]
### BUG描述

我尝试更新Velocity版本以支持1.21.2，但是遇到了MUiltLogin抛出的错误。

### MultiLogin版本

v0.6.12

### 系统架构

linux/amd64

### 服务器核心

Velocity/3.4.0-Build#444

### 配置文件

https://paste.fastmirror.net/?549e4b0846ec541f#Azpt4R9NfNjjpD3Ts299j8w6UVLU1HzL5GiPvMz9xsym

（此处的配置文件还未开启Debug，发送的日志已开启Debug）
### 日志

https://paste.fastmirror.net/?e89d75b5ce955b68#43rLRmxPtja7YDcFKcv9dXWsuYzZ2wb6Qb5qhgs518uN

### 复现步骤

1.下载Velocity 3.4.0-SNAPSHOT（BUild444）
2.将本插件放入plugins
3.启动

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by CaaMoe** [comment]
chat session blocker是没用的功能，在最新的提交中已将他删掉
