### ISSUE TITLE
[错误报告] 关于中文字符的支持

### ISSUE THREAD

**Issue by ning-g-mo** [CaaMoe/MultiLogin#187]
### BUG描述

utf-8编码范围写进去了，但是无法登录皮肤站的中文名称进入服务器

### MultiLogin版本

0.6.11

### 系统架构

Windows 11 AMD64

### 服务器核心

leaves1.21.1

### 配置文件

https://api.mclo.gs/1/raw/DHeAGHn

### 日志

https://api.mclo.gs/1/raw/VZgHvlL

### 复现步骤

1.
2.
3.
...

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by CaaMoe** [comment]
`^[0-9a-zA-Z_\u4e00-\u9fa5]{3,16}$`
