### ISSUE TITLE
正版无法登入

### ISSUE THREAD

**Issue by Huaxidesu** [CaaMoe/MultiLogin#2]
问题在这里https://www.mcbbs.net/forum.php?mod=viewthread&tid=1147850&page=1&authorid=707541

**Comment by CaaMoe** [comment]
理论上新玩家在所设置的某个验证服务器验证通过后，以后登入就只能通过那种验证方式进入游戏了。这是账号保护的功能。
用来防止在多ygg的情况下出现重uuid账户而造成玩家财产损失。

**Comment by CaaMoe** [comment]
MCBBS插件发布帖下的签名档有我的QID，如果对此问题仍有疑问的话，请联系我。
