### ISSUE TITLE
一些关于设置在BC上的问题

### ISSUE THREAD

**Issue by AkariDream** [CaaMoe/MultiLogin#29]
1.littleskin设置后不能使用 我怀疑我配置错误了
*但是我不知道该使他生效
  littleskin:
  name: "littleskin"
  body:
      url: "https://littleskin.cn/api/yggdrasil/sessionserver/session/minecraft/hasJoined?username={username}&serverId={serverId}"

2.当我使用正版进入游戏然后被踢出游戏
踢出原因:你没有足够的白名单权限进入服务器
*当我使用统一通行证时 这样的问题也发生了

**Comment by AkariDream** [comment]
关于这一行的url
url: _"https://littleskin.cn{...}={serverId}"
我加了{passIpContent} 但是仍然不能工作
*我复制的时候正在尝试删除了这段之后能不能工作
*好像不行

**Comment by CaaMoe** [comment]
请提供plugins/multilogin/logs/latest.log

字面意思，你没有足够的白名单权限进入服务器。
解决办法：
1、关闭MultiLogin内置白名单程序
2、使用/MultiLogin:whitelist add <name> 来添加白名单
