### ISSUE TITLE
是否可能支持forge？

### ISSUE THREAD

**Issue by huangsijun17** [CaaMoe/MultiLogin#30]
最好能支持1.7.10等版本。GT啊TAT。

**Comment by BecodReyes** [comment]
> **支持 Velocity、Bungee、Bukkit、Fabric**

纯forge请套一个转发层
插件+mod混合端直接使用

另外

> 1.7.10原本就不安全
不应该在服务器端使用
multilogin设计初衷就是登陆安全
不符合设计理念

> 怎么还有人在开1.7.10

**Comment by huangsijun17** [comment]
> > **支持 Velocity、Bungee、Bukkit、Fabric**
> 
> 纯forge请套一个转发层 插件+mod混合端直接使用
> 
> 另外
> 
> > 1.7.10原本就不安全
> > 不应该在服务器端使用
> > multilogin设计初衷就是登陆安全
> > 不符合设计理念
> 
> > 怎么还有人在开1.7.10

GTNH GTNH GTNH 问格雷和整合包作者啊……

**Comment by CaaMoe** [comment]
理论上猫踢螺钉是不会对非代理端提供后续支持服务的，请套一个转发层
