### ISSUE TITLE
对Geyser的支持

### ISSUE THREAD

**Issue by Dreamail** [CaaMoe/MultiLogin#31]
如题，使用Geyser-Spigot并用PE端连接服务器时，无论使用正版账号还是外置皮肤站账号，均会提示无效登陆信息
当添加authlib java agent时，指定外置皮肤站yggdrasil。使用外置登陆信息可以进入，但正版登陆信息依然无法登陆

**Comment by CaaMoe** [comment]
插件运行时不需要使用authlib-injector程序，关于无效的登录信息，你可使用最新的构建版本或使用发行的代理版本来解决。有关于正版无法验证，可能是设置错误或验证服务器宕机导致的。你可以添加项目页下的扣扣群了解使用详情。

**Comment by Dreamail** [comment]
多次测试仍如此，现在已经放弃了，打javaagent让PE玩家必须用外置算了。

**Comment by srlss123** [comment]
PE端没有所谓的外置或者正版账户
手机上只有所谓的“基岩版” 当你使用Xbox账户 也就是微软账户登陆后 配置间歇泉+Floodgate即可实现登录操作
使用Multilogin时不需要再启动参数后添加authlib-injector，仅仅需要修改成正版验证。
使用间歇泉时必须配合Floodgate 否则登录无效化
此外 请使用最新版本的Multilogin插件 否则会被拦截

**Comment by DreamOneX** [comment]
[Dreamail/Geyser](https://github.com/Dreamail/Geyser) 这个fork实现了Geyser对Multilogin的支持，微软登录与外置登录通过测试
