### ISSUE TITLE
[问题] 想问下，这款插件支持java8吗？

### ISSUE THREAD

**Issue by 000214075** [CaaMoe/MultiLogin#35]
### 描述功能请求

这款插件支持java8吗？
以后有支持java8的打算吗？

### 请确认此建议所影响的内容

- [ ] 文档
- [ ] 安装
- [x] 可扩展性
- [ ] 安全
- [x] 用户体验
- [ ] 测试和发布
- [x] 开发架构
- [x] 新的扩展
- [ ] 其他

**Comment by CaaMoe** [comment]
目前主分支（版本暂定0.5）尚未发布任何一个版本，请切换至 master 分支，它将支持 Java 8，请使用 0.3.x。
