### ISSUE TITLE
bungeecord上初始化修改失败

### ISSUE THREAD

**Issue by fulide** [CaaMoe/MultiLogin#4]
测试环境
jdk11
bungeecord#1545-#1548
无其他插件
![image](https://user-images.githubusercontent.com/79419182/108879810-967fb800-763c-11eb-98df-6f7bd7098168.png)

**Comment by CaaMoe** [comment]
这是一个bug，目前项目正在重写，感谢反馈

**Comment by ksqeib445** [comment]
已修复
