### ISSUE TITLE
[错误报告] 

### ISSUE THREAD

**Issue by 864063334** [CaaMoe/MultiLogin#41]
### BUG描述

![QQ截图20220509151804](https://user-images.githubusercontent.com/61329086/167359430-f88a92f5-bbd5-480c-b2c4-be81f3b3037f.png)

### MultiLogin版本

MultiLogin-Velocity-0.3.14

### 系统架构

velocity-3.1.2-SNAPSHOT-136
windows server 2022

### 配置文件

[velocity.zip](https://github.com/CaaMoe/MultiLogin/files/8649533/velocity.zip)
这个是我的速度配置
插件本身无修改，直接装入的

### 日志

[latest.log](https://github.com/CaaMoe/MultiLogin/files/8649542/latest.log)

### 复现步骤

1.装入MultiLogin插件
2.报错
3.回车关闭
...

### 确认一遍

- [x] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by CaaMoe** [comment]
`正版验证处于关闭状态，插件不能正常运行，请开启它`

**Comment by 864063334** [comment]
> `正版验证处于关闭状态，插件不能正常运行，请开启它`

可以运行了捏，还有个问题就是子服的paper.yml内的
  velocity-support:
    enabled: true
    online-mode: false
这里的正版验证也要开启吗

**Comment by CaaMoe** [comment]
guess..
