### ISSUE TITLE
[错误报告]  最新构建版有严重的性能问题

### ISSUE THREAD

**Issue by LittleHed** [CaaMoe/MultiLogin#44]
### BUG描述

服务器版本为Purpur(build1640) - 1.19 (Java18)
multilogin插件疑似有严重的性能影响
测试时服务器均为1人
图1为不安装multilogin时的TPS与MSPT情况
![image](https://user-images.githubusercontent.com/58099834/173109349-26797e8d-7f57-49e0-85ec-448a4f718e41.png)
图2为安装了multilogin后的情况，可见服务器TPS明显下降
![image](https://user-images.githubusercontent.com/58099834/173111306-31a9dbf3-925b-4937-a2a7-33790d139604.png)
![image](https://user-images.githubusercontent.com/58099834/173111684-4d268569-1db9-45a2-af32-9fcc0603a1b7.png)
https://spark.lucko.me/pjJ7LVwpqG

### MultiLogin版本

Build_1654861664

### 系统架构

Windows/amd64

### 配置文件

原配置

### 日志

日志无任何报错

### 复现步骤

分别在安装和不按照multilogin的情况下开启服务器，然后使用spark查询服务器情况

### 确认一遍

- [x] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by DJelly4K** [comment]
![IMG_20220611_074557](https://user-images.githubusercontent.com/68630033/173163351-8c7b8a0a-012c-4367-9b7d-1a2e35fed037.jpg)

**Comment by CaaMoe** [comment]
测试时并未发现此类问题，使用spigot 1.19:
未装 MultiLogin: [sv](https://spark.lucko.me/KesuSoFuAs)
使用构建版 MultiLogin: [sv](https://spark.lucko.me/cAJI6D8Jp8)

**Comment by LittleHed** [comment]
更新Purpur服务端版本后性能问题已解决
