### ISSUE TITLE
[错误报告] 使用Velocity最新版本无法进入服务器

### ISSUE THREAD

**Issue by Chino081** [CaaMoe/MultiLogin#45]
### BUG描述

使用最新版本velocity-3.1.2-SNAPSHOT-151，加入MultiLogin插件会导致无法进入服务器提示 连接中止 后台无任何报错

### MultiLogin版本

0.3.14

### 系统架构

windows/amd64

### 配置文件

无

### 复现步骤

1.
2.
3.
...

### 确认一遍

- [x] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by BecodReyes** [comment]
`velocity-3.1.2` 尚处开发状态

待转为稳定版之后再去支持
