### ISSUE TITLE
[建议] 增加http或者socks5代理

### ISSUE THREAD

**Issue by roughanddai** [CaaMoe/MultiLogin#46]
### 描述功能请求

希望可以增加代理支援  例如将玩家请求途径本地的socks5服务器转发，减少出现因为网路问题验证失败的问题

### 请确认此建议所影响的内容

- [ ] 文档
- [ ] 安装
- [ ] 可扩展性
- [ ] 安全
- [x] 用户体验
- [ ] 测试和发布
- [ ] 开发架构
- [ ] 新的扩展
- [ ] 其他

**Comment by BecodReyes** [comment]
[yggdrasil-服务端配置例子](https://github.com/CaaMoe/MultiLogin/wiki#yggdrasil-%E6%9C%8D%E5%8A%A1%E7%AB%AF%E9%85%8D%E7%BD%AE%E4%BE%8B%E5%AD%90)

临时解决方案：反代世界树

**Comment by First-Dream** [comment]
更简单的方法，Velocity JVM参数添加 -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=8080 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=8080 不过此参数对所有http连接都生效，可能需要在代理服务器上做分流

**Comment by CatMoe** [comment]
将在v5中实现

**Comment by CaaMoe** [comment]
已在 v5 实现
