### ISSUE TITLE
[建议] 关于对geyser支持

### ISSUE THREAD

**Issue by TaylorEevee** [CaaMoe/MultiLogin#48]
### 描述功能请求

我使用了geyser-spigot来搭建双版本互联，以及使用了multilogin，但是我发现如果geyser想走第三方登录必须侧挂authlib，我设置完成后发现基岩版使用geyser登录时可以使用第三方的账号进行登录，但是如果正版Java玩家想使用基岩版登录时会被告知[此服务器需要一个付费的java账号]

### 请确认此建议所影响的内容

- [ ] 文档
- [ ] 安装
- [ ] 可扩展性
- [ ] 安全
- [x] 用户体验
- [ ] 测试和发布
- [ ] 开发架构
- [ ] 新的扩展
- [ ] 其他

**Comment by CaaMoe** [comment]
使用 `floodgate`

**Comment by TaylorEevee** [comment]
可是使用floodgate的话皮肤站的用户要怎么登录emmmm

**Comment by CatMoe** [comment]
bedrock用户特殊管理，毕竟反作弊什么的都要特殊管理，没道理不用

**Comment by DJelly4K** [comment]
> 可是使用floodgate的话皮肤站的用户要怎么登录emmmm

你不能让皮肤站用户和基岩版用户绑定吗

**Comment by TaylorEevee** [comment]
> > 可是使用floodgate的话皮肤站的用户要怎么登录emmmm
> 
> 你不能让皮肤站用户和基岩版用户绑定吗

emmm,floodgate的绑定不是要在java版操作吗，我服很多玩家没有java版本游戏，而且，如果基岩版先登录的话，floodgate自带的uuid算法会把数据同步搞的乱七八糟，这时再绑定账号做数据迁移要累死

**Comment by srlss123** [comment]
1.请不要把基岩版玩家当正常玩家看，早晚你都得后悔
2.请不要试图给基岩版玩家提供皮肤站登陆，早晚会有安全性问题
3.间歇泉支持/linkaccount往java版，并且能正常显示基岩版玩家皮肤，所以皮肤站意义何在？让基岩版玩家分成2个登陆有啥意义。
4.基岩版账号id是唯一的 使用floodgate的前缀功能可以使得玩家是唯一的，而不用担心安全性问题。

我知道你这个问题想说什么，无非就是想让基岩版玩家和java版玩家进入后同ID即可实现直接游玩而不需要使用任何指令，但我想说，**这不可能实现**，请不要试图干这种事。

实际上，你可以使用离线模式，但请不要试图使用混合。。。。。

**重申一遍 不可能支持基岩版混合**

**Comment by TaylorEevee** [comment]
> bedrock用户特殊管理，毕竟反作弊什么的都要特殊管理，没道理不用

我服上周目就是floodgate，那插件的uuid算法一度让我搞数据同步搞的十分头大

**Comment by srlss123** [comment]
请 不 要 考 虑 在 混 合 登 陆 下 的 java 与 bedrock player 的 直 接 互 通

再说 你这个问题应该找flootgate（

**Comment by TaylorEevee** [comment]
> 请 不 要 考 虑 在 混 合 登 陆 下 的 java 与 bedrock player 的 直 接 互 通
> 
> 再说 你这个问题应该找flootgate（

就是因为上一次用吐了我打死也不想用floodgate（

**Comment by CatMoe** [comment]
你多服同步的话，直接在bungee上处理就好了，floodgate的绑定也只是uuid的转换，不明白你这个数据同步为什么会这么困难

**Comment by srlss123** [comment]
所以你让java混合登陆 纯属是给自己找事做。。。。

**Comment by srlss123** [comment]
你要是离线登录 也不至于麻烦到这个地步

**Comment by DJelly4K** [comment]
锁issue得了

**Comment by srlss123** [comment]
此外，请不要在multilogin这里寻求基岩版支持。
作者一度还直接把基岩版拦截了。。。。
**所以 请你不要在这里继续寻求支持了~**

**Comment by BecodReyes** [comment]
**为什么一定要兼容基岩版**

**让手机兼容java版不好么**

**这样纯属是给自己找事做**
