### ISSUE TITLE
[Question] How to configure message.properties?

### ISSUE THREAD

**Issue by KOTOKOPOlb** [CaaMoe/MultiLogin#50]
I apologize for possible spelling errors.

**Describe feature request**
The instructions say to create a message.properties file. I created it, but how do I set it up? I would like to translate the plugin into Russian or English.

**Describe the alternatives you have considered**
_No response_

**Please confirm what this suggestion affects**

- [ ] Documentation
- [ ] Install
- [ ] Scalability
- [ ] Safety
- [x] user experience
- [ ] test and release
- [ ] Development Architecture
- [ ] new extension
- [ ] other

**Comment by CatMoe** [comment]
see here
[https://github.com/CaaMoe/MultiLogin/blob/master/core/src/main/resources/message.properties](https://github.com/CaaMoe/MultiLogin/blob/master/core/src/main/resources/message.properties)
This is the built in language file
