### ISSUE TITLE
[Bug Report] Incorrect display of Russian letters

### ISSUE THREAD

**Issue by KOTOKOPOlb** [CaaMoe/MultiLogin#53]
### Bug Description

When using Russian letters in the UTF-8 or OEM 866 encoded message.properties file, the letters are displayed as **a??? eKOTOKOPOLba ???????? ? ???? ??!** or **╚уЁюъ KOTOKOPOLb фюсртыхэ т схы√щ ёяшёюъ!** instead of  **Игрок KOTOKOPOLb добавлен в белый список!**.

### MultiLogin Version

The license check from Microsoft and from the site Ely.by is used.

### System Architecture

windows/amd64

### Configurations

services:
  official:
    name: "Minecraft official"
    body:
      url: "https://sessionserver.mojang.com/session/minecraft/hasJoined?username={username}&serverId={serverId}" 

  elyby:
    enable: true
    name: "Ely.by version"
    body:
      url: "https://authserver.ely.by/session/hasJoined?username={username}&serverId={serverId}"
      postMode: false
      passIp: false
      passIpContent: "&ip={ip}"
      postContent: '{"username":"{username}", "serverId":"{serverId}"'
    convUuid: DEFAULT
    convRepeat: false
    nameAllowedRegular: ''
    whitelist: false
    refuseRepeatedLogin: true
    authRetry: 3
    skinRestorer: OFF
    skinRestorerRetry: 2

servicesTimeOut: 10000
whitelist: true
nameAllowedRegular: '^[0-9a-zA-Z_]{1,16}$'

sql:
  backend: H2
  ip: '127.0.0.1'
  port: 3306
  username: @@@@@@
  password: @@@@@@@
  database: 'multilogin'
  prefix: 'multilogin'

### Steps to reproduce

1. Changing the **message.properties** file
2. Saving a file
3. Plugin reload or server restart

### Affected area

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by CaaMoe** [comment]
Using `UTF-8`, try again

**Comment by KOTOKOPOlb** [comment]
Does not work, it writes **�a??? �eKOTOKOPOLb�a ???????? ? ???? ??!**

**Comment by BecodReyes** [comment]
![image.png](https://s2.loli.net/2022/07/05/VH5pjMfz2F7YUAX.png)

Unable to reproduce, please check your file encoding problem.

Debian 11
Velocity-3.1.2
f74620205af3f108475a9c63cc382e552a06c300

**Comment by KOTOKOPOlb** [comment]
Right now I don't have access to my Windows 10, I tried it through Ubuntu Server and it works! The problem is cmd windows 10. Have no idea how to fix this?

**Comment by KOTOKOPOlb** [comment]
Why can't I fix it? I fixed it! It was just necessary to slightly change the server start parameters and start.bat.
Was: `@echo OFF
java -Xmx2048M -DIReallyKnowWhatIAmDoingISwear=true -jar spigot-1.16.4.jar nogui
pause`
Now: `chcp 65001
@echo OFF
java -Xmx2048M -Dfile.encoding=UTF-8 -DIReallyKnowWhatIAmDoingISwear=true -jar spigot-1.16.4.jar nogui
pause`
