### ISSUE TITLE
[Bug Report] 不兼容 authlib-injector 1.2.0

### ISSUE THREAD

**Issue by yushijinhun** [CaaMoe/MultiLogin#56]
### Bug Description

当用户使用 authlib-injector 1.2.0 的客户端，进入使用 MultiLogin 的 1.19+ 服务器时，会报 `Invalid signature for profile public key. Try restarting your game.` 错误。

细节请参考 [authlib-injector v1.2.0 Release Notes](https://github.com/yushijinhun/authlib-injector/releases/tag/v1.2.0) 以及 [https://github.com/yushijinhun/authlib-injector/discussions/158](https://github.com/yushijinhun/authlib-injector/discussions/158)。authlib-injector 为了应对 Minecraft 1.19 的聊天消息签名机制，在 v1.2.0 版本中会向服务端发送一个随机生成的 Profile Key，以及内容为一个零字节的数字签名，代码实现参考[此处](https://github.com/yushijinhun/authlib-injector/blob/develop/src/main/java/moe/yushi/authlibinjector/httpd/ProfileKeyFilter.java#L54-L82)。服务端校验 Profile Key 的签名时，不论内容如何，校验结果应始终通过，代码实现参考[此处](https://github.com/yushijinhun/authlib-injector/blob/develop/src/main/java/moe/yushi/authlibinjector/transform/support/YggdrasilKeyTransformUnit.java#L84-L132)。

这一改动将消除聊天消息中的感叹号，并且将允许服务端开启 `enforce-secure-profile`，以消除进入服务器时聊天消息可能被修改的警告。

但因为不论服务端是否启用 `enforce-secure-profile`，只要客户端发送了 Profile Key，服务端始终会校验其数字签名，并且在签名无效的情况下将会断开链接。因此，服务端必须使用措施绕过签名校验。对于使用 authlib-injector 的服务端，将版本升级到 v1.2.0 即可；而对于使用 MultiLogin 的服务端，目前 MultiLogin 暂不支持此功能。

### MultiLogin Version

All versions

### System Architecture

All architectures

### Configurations

N/A

### Affected area

- [ ] I included all information required in the sections above
- [ ] I made sure there are no duplicates of this report [(Use Search)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by SistineFibelKen** [comment]
刚刚遇到一样的问题，原来是这个原因。

**Comment by 2623684696** [comment]
还好我还没用

**Comment by CaaMoe** [comment]
[v0.3.16](https://github.com/CaaMoe/MultiLogin/releases/tag/v0.3.16)
[v0.5.0-ALPHA.5](https://github.com/CaaMoe/MultiLogin/releases/tag/v0.5.0-ALPHA.5)
