### ISSUE TITLE
无法使用互通插件
他会提醒需要java
导致使用互通登录的基岩版玩家无法正常进入


### ISSUE THREAD

**Issue by 2623684696** [CaaMoe/MultiLogin#57]

**Comment by 2623684696** [comment]
我开互通的，我又想管理，我总我两个不能扔一个。
正常来说应该是能获取到登录网址。
uuid应该也有。

**Comment by 2623684696** [comment]
更大的原因是插件是必须需要提供正版验证的。

**Comment by DJelly4K** [comment]
你用floodgate了吗

**Comment by Becods** [comment]
请使用模板回报bug

**Comment by 2623684696** [comment]
> 你用floodgate了吗

这什么意思？

**Comment by Kimiblock** [comment]
> 

floodgate允许玩家使用基岩版帐号登录Java服务器. 如果不使用floodgate玩家就必须拥有Java正版才能游玩...
https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/master/

**Comment by 2623684696** [comment]
但他好像不开正版验证就无法启动。

**Comment by 2623684696** [comment]
但是我只要开了。用互通进来，他就会提醒需要账号。

**Comment by Kimiblock** [comment]
我是开了online-mode然后加了Geyser和Floodgate
基岩版游玩完全没问题, 也不需要Java帐号

可能是你的Floodgate没加 / Geyser配置文件里没开 Floodgate验证

**Comment by 2623684696** [comment]
我的朋友进我的服的时候，他会有那个提醒。

**Comment by 2623684696** [comment]
> 我是开了online-mode然后加了Geyser和Floodgate
> 基岩版游玩完全没问题, 也不需要Java帐号
> 
> 可能是你的Floodgate没加 / Geyser配置文件里没开 Floodgate验证

具体是这两个中的哪个选项？

**Comment by Kimiblock** [comment]
![1](https://user-images.githubusercontent.com/61745317/183426888-f0668194-1d41-431f-8383-5a4d606ba44a.png)

**Comment by 2623684696** [comment]
> ![1](https://user-images.githubusercontent.com/61745317/183426888-f0668194-1d41-431f-8383-5a4d606ba44a.png)
> 

但要这么改的话，连进都进不去。

**Comment by Kimiblock** [comment]
> > ![1](https://user-images.githubusercontent.com/61745317/183426888-f0668194-1d41-431f-8383-5a4d606ba44a.png)
> 
> 但要这么改的话，连进都进不去。

应该是你的Floodgate没安装
https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/master/lastSuccessfulBuild/artifact/spigot/build/libs/floodgate-spigot.jar

**Comment by LittleChest** [comment]
同样的问题
使用Waterfall（BungeeCord）+ Geyser-Bungee
在所有子服上安装了Floodgate和MultiLogin
