### ISSUE TITLE
无法使用互通

### ISSUE THREAD

**Issue by 2623684696** [CaaMoe/MultiLogin#58]
### Bug Description

因为互通它是需要关闭正版验证的，但是。插件没有正版验证又无法运行，导致他俩压根没法同时存在
只要能想办法，让他俩能共存，或者能在不开正版验证的状态下启动。

### MultiLogin Version

3.15

### System Architecture

windows

### Configurations

1.19 互通插件 ess

### Steps to reproduce

1.
2.
3.
...

### Affected area

- [ ] I included all information required in the sections above
- [ ] I made sure there are no duplicates of this report [(Use Search)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by Becods** [comment]
请换互通插件

正版验证是永远不会支持关闭的

> 拒绝 安全性问题太大
> 不符合产品预期

 https://github.com/CaaMoe/MultiLogin/issues/17#issuecomment-891563001 < 如果不想再被骂的话欢迎继续回报
