### ISSUE TITLE
linux下乱码

### ISSUE THREAD

**Issue by ghhcbef** [CaaMoe/MultiLogin#6]
jdk11
bungeecord
![图片](https://user-images.githubusercontent.com/63829337/122666229-b7b57700-d1de-11eb-8004-2248c6a058de.png)

**Comment by ghhcbef** [comment]
![图片](https://user-images.githubusercontent.com/63829337/122666320-24c90c80-d1df-11eb-85b5-c0524bb067f9.png)

**Comment by CaaMoe** [comment]
应该试图改变一下config.yml的文件编码格式，再次尝试。
