### ISSUE TITLE
[Bug Report] where is fabric 1.19 version

### ISSUE THREAD

**Issue by Pickymarker** [CaaMoe/MultiLogin#60]
### Bug Description

[Bug Report] where is fabric 1.19 version

### MultiLogin Version

latest

### System Architecture

windows

### Configurations

where is fabric 1.19 version

### Logs

where is fabric 1.19 version

### Steps to reproduce

where is fabric 1.19 version

### Affected area

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by Becods** [comment]
Using velocity.

The addition of the secure chat feature in 1.19.1 broke most of the functionality and the developers are working on fixing it.

**Comment by Pickymarker** [comment]
i can't get it to let me make a pull request

**Comment by Pickymarker** [comment]
and also, is there a 1.18.2 fabric version of multilogin  and if so does it have viafabric and viabackwards support

**Comment by CaaMoe** [comment]
https://github.com/CaaMoe/MultiLogin/releases/tag/v1.0-RC.3

For some reason, the development of the Fabric version of multilogin has been suspended, please wait for the later version
