### ISSUE TITLE
do you know a unified pass alternative for usa or that does not require qq and what version is for 1.18.2 velocity

### ISSUE THREAD

**Issue by Pickymarker** [CaaMoe/MultiLogin#61]
### Bug Description

do you know a unified pass alternative for usa or that does not require qq and what version is for 1.18.2 velocity

### MultiLogin Version

do you know a unified pass alternative for usa or that does not require qq and what version is for 1.18.2 velocity

### System Architecture

do you know a unified pass alternative for usa or that does not require qq and what version is for 1.18.2 velocity

### Configurations

do you know a unified pass alternative for usa or that does not require qq and what version is for 1.18.2 velocity

### Logs

do you know a unified pass alternative for usa or that does not require qq and what version is for 1.18.2 velocity

### Steps to reproduce

do you know a unified pass alternative for usa or that does not require qq and what version is for 1.18.2 velocity

### Affected area

- [x] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by Becods** [comment]
If you need a self-hosted third party user system, check out [bs-community/blessing-skin-server](https://github.com/bs-community/blessing-skin-server).

This plugin simply enables you to use multiple yggdrasil logins to the same server.

> Yggdrasil is the name of the authentication system that is currently used for authenticating user credentials for Minecraft.

**Comment by Pickymarker** [comment]
but where can i get authlib injector 1.18.2 fabric

**Comment by Becods** [comment]
After installing multilogin you no longer need to use the authlib injector.

**Comment by Pickymarker** [comment]
but where is the 1.18.2 fabric version of multilogin

**Comment by Becods** [comment]
[v1.0-RC.3](https://github.com/CaaMoe/MultiLogin/releases/tag/v1.0-RC.3)
