### ISSUE TITLE
[错误报告] 不兼容1.19.2

### ISSUE THREAD

**Issue by little-creeper** [CaaMoe/MultiLogin#62]
### BUG描述

当1.19.2版本的外置登录玩家说话时，1.19.2版本正版登录玩家将会掉线并提示"聊天消息验证失败"
![NRUTEWLM}WE5IHG$6NQ``1X](https://user-images.githubusercontent.com/77864650/186324097-8222de1e-2b44-4696-b289-2cea20fd6d17.png)
后台截图
![XD``A2WWS5N WI)IJNT4(TA](https://user-images.githubusercontent.com/77864650/186323859-380314a6-7ddd-4f41-9c79-d3acd5606e82.png)
---
注意：使用外置登录和正版登录玩家的聊天前缀**不会显示**[Not Secure]，而使用1.19.1登陆的玩家、基岩版玩家以及开启BakaXL禁用聊天举报的1.19.2玩家聊天前缀则会显示，当外置登录玩家说话时这些玩家不会掉线。

### MultiLogin版本

v0.3.16

### 系统架构

linux/amd64

### 配置文件

[PasteBin](https://paste.fastmirror.net/?c0c88002b0afb78e#7fsuPPUkRwzgmJ4oFSohwxmHMR3rR58S6gRWhrP9f3SY)

### 日志

![image](https://user-images.githubusercontent.com/77864650/186324409-8aec56e8-c0a1-4584-ac33-4d6fcb835f1e.png)
此外无报错日志

### 复现步骤

1.1.19.2外置登录玩家和正版登录玩家同时进入服务器
2.1.19.2外置登录玩家说话
3.1.19.2正版登录玩家被强制退出游戏并提示“聊天消息验证失败”
...

### 确认一遍

- [x] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by Becods** [comment]
临时修复 [Oharass/FreedomChat](https://github.com/Oharass/FreedomChat)

我们会在 [QQ群](https://jq.qq.com/?_wv=1027&k=WrOTGIC7) 里讨论新的bug和解决方案，直到测试方案稳定可行后才会在仓库更新

**Comment by little-creeper** [comment]
QQ群验证答案是什么？尝试了多次不让进

**Comment by Becods** [comment]
世界树英文是什么呢？世界树相信大家都很熟悉，但是世界树英文是什么是怎么回事呢，下面就让小编带大家一起了解吧。

世界树英文是什么，其实就是世界树英文，大家可能会很惊讶世界树英文怎么会是什么呢？但事实就是这样，小编也感到非常惊讶。

这就是关于世界树英文是什么的事情了，大家有什么想法呢，欢迎在评论区告诉小编一起讨论哦！
