### ISSUE TITLE
[建议] 配置说明

### ISSUE THREAD

**Issue by mrcuncun** [CaaMoe/MultiLogin#65]
### 描述功能请求

wiki的配置说明没看懂，按着设置了运行不起来，有没有配置文件的范本？

### 请确认此建议所影响的内容

- [ ] 文档
- [ ] 安装
- [ ] 可扩展性
- [ ] 安全
- [ ] 用户体验
- [ ] 测试和发布
- [ ] 开发架构
- [ ] 新的扩展
- [ ] 其他

**Comment by CaaMoe** [comment]
https://github.com/CaaMoe/MultiLogin/tree/v5/core/src/main/resources/examples
