### ISSUE TITLE
[错误报告] arclight1.18.2上运行MultiLogin崩溃

### ISSUE THREAD

**Issue by TaylorEevee** [CaaMoe/MultiLogin#69]
### BUG描述

服务端版本arclight-forge-1.18.2-1.0.7-SNAPSHOT.jar
只安装了multilogin v0.5.1
启动后就崩溃

### MultiLogin版本

MultiLogin v0.5.1

### 系统架构

windows/amd64

### 配置文件

插件并未生成配置文档

### 日志

https://bytebin.lucko.me/PgyCIG2mb7

### 复现步骤

1.安装MultiLogin
2·启动服务器

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by CaaMoe** [comment]
不支持混合端

**Comment by TaylorEevee** [comment]
> 不支持混合端

那请问一下我有这个需求的话有什么解决方法吗

**Comment by CaaMoe** [comment]
在外面套一层velocity，或是使用v3老版本
