### ISSUE TITLE
[建议] 上传至Modrinth

### ISSUE THREAD

**Issue by SulfuricM** [CaaMoe/MultiLogin#71]
### 描述功能请求

Modrinth对国内用户来说较为友好

### 请确认此建议所影响的内容

- [ ] 文档
- [ ] 安装
- [ ] 可扩展性
- [ ] 安全
- [X] 用户体验
- [X] 测试和发布
- [ ] 开发架构
- [ ] 新的扩展
- [ ] 其他

**Comment by CaaMoe** [comment]
是的，我们正在考虑这件事，但是真正有多世界树需求的服务器实在是太少太少了，甚至由于多世界共存的安全性他一直都不受待见，所以目前还是没有计划添加上去。
