### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by Sinetian** [CaaMoe/MultiLogin#72]
### Bug Description

进行启动时在下载界面卡了好久

### MultiLogin Version

0.5.1

### System Architecture

linux、amd64

### Configurations

首次启动

### Steps to reproduce

1.
2.
3.
...

### Affected area

- [ ] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by Becods** [comment]
非MultiLogin导致的问题

请检查网络连接是否通畅

**Comment by Sinetian** [comment]
thanks
