### ISSUE TITLE
mohist不支持

### ISSUE THREAD

**Issue by happytbs** [CaaMoe/MultiLogin#74]
![image](https://user-images.githubusercontent.com/74001578/205472727-a8924483-7365-458c-8ea8-eaef3207d9cb.png)
https://github.com/MohistMC/Mohist/issues/2384#issuecomment-1334864481
一启动就闪退

**Comment by CaaMoe** [comment]
不支持混合端，请使用 Velocity 代理版本或寻找其他有共存功能的插件或程序[MultiYggdrasil](https://github.com/YuxuanZuo/MultiYggdrasil)、[YggdrasilOfficialProxy](https://github.com/YggdrasilOfficialProxy/YggdrasilOfficialProxy)
