### ISSUE TITLE
希望能够支持 Velocity

### ISSUE THREAD

**Issue by BecodReyes** [CaaMoe/MultiLogin#8]
希望能够支持 [Velocity](https://velocitypowered.com/)
我知道这个可能会造成较大工作量，但是 [Velocity](https://velocitypowered.com/) 在性能和资源使用方面仍然遥遥领先于 [Bungeecord](https://www.spigotmc.org/wiki/bungeecord/) ，并且使用者越来越多，因此我诚挚的希望能够支持 [Velocity](https://velocitypowered.com/)
如果此建议被驳回，我可以理解，毕竟 [Velocity](https://velocitypowered.com/) 使用了新的 [API](https://velocitypowered.com/wiki/developers/api-basics/)，并且作为新生的软件所提供的文档详细度是不能与 [Bungeecord](https://www.spigotmc.org/wiki/bungeecord/) 这种老牌所相比的，如果要支持那就等同于增加了插件开发和维护的成本

**Comment by CaaMoe** [comment]
针对 Velocity 版本的 MultiLogin 将在不久后推出，请耐心等待。

**Comment by ksqeib445** [comment]
感谢您的支持 velocity现已支持
