### ISSUE TITLE
Wiki指令部分有误

### ISSUE THREAD

**Issue by AlexXuCN** [CaaMoe/MultiLogin#82]
现有wiki的 # 指令和权限 部分的

|/multilogin remove priflle &lt;yggdrasilId&gt; &lt;onlineUUID&gt;								|command.multilogin.remove.profile				|移除一份在线游戏档案				|

一行有误
经实际测试 指令应为`/multilogin user remove profile  <yggdrasilId> <onlineUUID>
![图片](https://user-images.githubusercontent.com/48176762/209454395-f85f0ef8-fdca-4709-9cbb-3ba0260111a0.png)
以及 这里貌似还有个拼写错误（小声）
由于无法给wiki pr *我 改 不 了*

**Comment by Becods** [comment]
![image](https://user-images.githubusercontent.com/35525491/209471314-405aa642-4192-4d0c-9c98-966c6e0e5493.png) ![image](https://user-images.githubusercontent.com/35525491/209471318-ea9957ab-6587-4420-a985-e603bbcd49d6.png)

[Becods/MultiLoginPage](https://github.com/Becods/MultiLoginPage)
:point_up: 半官方教程页，欢迎前来完善 :point_up_2:

**Comment by CaaMoe** [comment]
已修正
