### ISSUE TITLE
有办法支持little skin的汉字ID登录吗？ [Feature Request] 

### ISSUE THREAD

**Issue by REver0** [CaaMoe/MultiLogin#91]
### Describe the feature request

在登录little skin的时候用了汉字的ID不能登录

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Extensions
- [ ] Others

**Comment by Becods** [comment]
https://github.com/CaaMoe/MultiLogin/blob/28188b776b26f5b3efbe0e551e6ef68f5759f7ea/core/src/main/resources/config.yml#L36-L41

**Comment by REver0** [comment]
留空了也会显示Username contains Invalid sharacters
![图片](https://user-images.githubusercontent.com/108091046/224476426-39cf231a-a2e1-4afb-9c06-b887b562c9e1.png)

**Comment by FallenCrystal** [comment]
> 留空了也会显示Username contains Invalid sharacters ![图片](https://user-images.githubusercontent.com/108091046/224476426-39cf231a-a2e1-4afb-9c06-b887b562c9e1.png)

使用原生BungeeCord 这不是插件能修改的.
