### ISSUE TITLE
[建议] 添加数据库迁移功能

### ISSUE THREAD

**Issue by ph59x** [CaaMoe/MultiLogin#92]
### 描述功能请求

实现数据在H2与MySql之间的相互迁移，使用类似于`/multilogin trans`的指令触发。

### 请确认此建议所影响的内容

- [ ] 文档
- [ ] 安全
- [x] 用户体验
- [ ] 新的扩展

**Comment by CaaMoe** [comment]
意义不大，使用市面上数据库工具都能实现数据迁移
