### ISSUE TITLE
[建议] 支持基岩版用户前缀功能

### ISSUE THREAD

**Issue by qyl27** [CaaMoe/MultiLogin#93]
### 描述功能请求

这是 Floodgate 的一个功能，给基岩版用户ID之前加前缀以区分。  
（或许可以被其他插件用来做什么专门为基岩版玩家设置的适配？）

### 描述你考虑过的备选方案

目前的备选方案是不使用 MultiLogin 管理 Floodgate 用户。

### 请确认此建议所影响的内容

- [ ] 文档
- [ ] 安装
- [X] 可扩展性
- [X] 安全
- [X] 用户体验
- [ ] 测试和发布
- [ ] 开发架构
- [ ] 新的扩展
- [ ] 其他

**Comment by CaaMoe** [comment]
从v6这个版本开始引入了身份卡的概念，游戏内名字已经和在线信息没太大关联了，以至于正版改名了加入游戏使用的还是改名前的名字，必须要手动更新。
