### ISSUE TITLE
[建议] Mohist兼容

### ISSUE THREAD

**Issue by 2623684696** [CaaMoe/MultiLogin#95]
### 描述功能请求

Mohist能用（（（

### 请确认此建议所影响的内容

- [ ] 文档
- [X] 安装
- [ ] 可扩展性
- [ ] 安全
- [ ] 用户体验
- [ ] 测试和发布
- [ ] 开发架构
- [x] 新的扩展
- [ ] 其他

**Comment by Becods** [comment]
bukkit 支持已弃用

请使用 bungeecord 或者 velocity 反代 mohist
