### ISSUE TITLE
[错误报告] Waterfall (Bungeecord) 在更新到新版插件时无法与部分插件兼容

### ISSUE THREAD

**Issue by wifi-left** [CaaMoe/MultiLogin#97]
### BUG描述

之前用的 v3，和这些插件是兼容的。
现在更新到 v6后，就无法启动了。
插件列表：
```
FallBackServer-3.1.2.jar
Geyser-BungeeCord.jar
PixelMOTD-9.3.5-SNAPSHOT.jar
ViaBackwards-4.6.2-SNAPSHOT.jar
floodgate.jar
mc_motd_mod-1.1-SNAPSHOT.jar
viaversion.jar
```
Floodgate 使用的是 `https://ci.kejona.dev/job/Floodgate/job/master/lastSuccessfulBuild/artifact/bungee/build/libs/floodgate-bungee.jar` 下载的修复一个bug后的版本，因为官方构建的 floodgate 的 Fourm Api 有bug。
Viaversion 均使用最新实验构建
Geyser 为最新构建。

### MultiLogin版本

v6.0.3

### 系统架构

windows/amd64

### 服务器核心

Waterfall

### 配置文件

无

### 日志

https://pastebin.mozilla.org/WaOkZM93

### 复现步骤

1. 删除v3版本插件
2. 安装v6.0.3
3. 无法启动服务器

### 确认一遍

- [X] 我已完成且认真地填写完了报告所需要的信息
- [X] 我确保没有重复的报告 [(搜索一下)](https://github.com/CaaMoe/MultiLogin/issues?q=is%3Aissue)

**Comment by wifi-left** [comment]
经测试，v5版本也是可以的，仅v6出现问题
日志有效期为21天

**Comment by wifi-left** [comment]
[2023-05-14-4.log.gz](https://github.com/CaaMoe/MultiLogin/files/11471119/2023-05-14-4.log.gz)

**Comment by CaaMoe** [comment]
服务器端网络不是很好，必须的依赖没有下载完全，重新踹一下

**Comment by wifi-left** [comment]
好像不是不好...
貌似库被404了
https://maven.aliyun.com/repository/public/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
这个界面是404
